# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-09-27 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190922_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=300, verbose_name='商品名'),
        ),
    ]
