# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-02 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191102_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='mobile',
        ),
    ]
