# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-03 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0004_hotsearchwords'),
        ('user_operation', '0002_auto_20190922_1247'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfav',
            unique_together=set([('user', 'goods')]),
        ),
    ]
